// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msziurxcplegxqwooawk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zeml1cnhjcGxlZ3hxd29vYXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxMTQ3NTUsImV4cCI6MjA3ODY5MDc1NX0.B5efBnsWSm_tRq0B1qu-XvByECd4ybPDaBseyVUHrXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});